<?xml version="1.0" ?><testsuite errors="0" failures="34" hostname="localhost" name="lettuce" tests="207" time="0" timestamp="2013-10-21T12:34:34"><testcase classname="Endpoint Modification : Partial update of an instance" name="| 0 | 0 | 0 | 0 |" time="0.000121"><failure message="classes_url"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/lettuce/core.py", line 144, in __call__
    ret = self.function(self.step, *args, **kw)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/capability_publication/endpoint_modification/steps.py", line 61, in a_capability_has_already_been_published_with_data
    api_utils.a_capability_has_already_been_published_with_data(step, old_cap_index)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/common/api_utils.py", line 320, in a_capability_has_already_been_published_with_data
    rest_utils.send_to_url_the_data(step, url_template, world.old_capability)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/common/rest_utils.py", line 82, in send_to_url_the_data
    url = self._get_url_with_values(url_template)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/common/rest_utils.py", line 365, in _get_url_with_values
    classes_url=world.config["django"]["classes_url"],
KeyError: 'classes_url'
]]></failure></testcase><testcase classname="Endpoint Modification : Modification of an endpoint when the DB is down_TDAFBA-489" name="| 0 | 0 | 0 | 0 |" time="6.5e-05"><failure message="classes_url"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/lettuce/core.py", line 144, in __call__
    ret = self.function(self.step, *args, **kw)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/capability_publication/endpoint_modification/steps.py", line 61, in a_capability_has_already_been_published_with_data
    api_utils.a_capability_has_already_been_published_with_data(step, old_cap_index)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/common/api_utils.py", line 320, in a_capability_has_already_been_published_with_data
    rest_utils.send_to_url_the_data(step, url_template, world.old_capability)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/common/rest_utils.py", line 82, in send_to_url_the_data
    url = self._get_url_with_values(url_template)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/common/rest_utils.py", line 365, in _get_url_with_values
    classes_url=world.config["django"]["classes_url"],
KeyError: 'classes_url'
]]></failure></testcase><testcase classname="Endpoint Modification : Publication of a new capability using unstructured data_TDAFBA-467" name="| 0 | 0 | 0 |" time="7.8e-05"><failure message="classes_url"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/lettuce/core.py", line 144, in __call__
    ret = self.function(self.step, *args, **kw)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/capability_publication/endpoint_modification/steps.py", line 61, in a_capability_has_already_been_published_with_data
    api_utils.a_capability_has_already_been_published_with_data(step, old_cap_index)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/common/api_utils.py", line 320, in a_capability_has_already_been_published_with_data
    rest_utils.send_to_url_the_data(step, url_template, world.old_capability)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/common/rest_utils.py", line 82, in send_to_url_the_data
    url = self._get_url_with_values(url_template)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/common/rest_utils.py", line 365, in _get_url_with_values
    classes_url=world.config["django"]["classes_url"],
KeyError: 'classes_url'
]]></failure></testcase><testcase classname="Endpoint Modification : Publication of a new capability using malformed data" name="| 0 | 0 | 0 |" time="7.1e-05"><failure message="classes_url"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/lettuce/core.py", line 144, in __call__
    ret = self.function(self.step, *args, **kw)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/capability_publication/endpoint_modification/steps.py", line 61, in a_capability_has_already_been_published_with_data
    api_utils.a_capability_has_already_been_published_with_data(step, old_cap_index)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/common/api_utils.py", line 320, in a_capability_has_already_been_published_with_data
    rest_utils.send_to_url_the_data(step, url_template, world.old_capability)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/common/rest_utils.py", line 82, in send_to_url_the_data
    url = self._get_url_with_values(url_template)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/common/rest_utils.py", line 365, in _get_url_with_values
    classes_url=world.config["django"]["classes_url"],
KeyError: 'classes_url'
]]></failure></testcase><testcase classname="Endpoint Modification : Modification of an endpoint of a non existing Cap" name="| 0 | 0 | 0 | 0 |" time="9.9e-05"><failure message="classes_url"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/lettuce/core.py", line 144, in __call__
    ret = self.function(self.step, *args, **kw)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/capability_publication/endpoint_modification/steps.py", line 61, in a_capability_has_already_been_published_with_data
    api_utils.a_capability_has_already_been_published_with_data(step, old_cap_index)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/common/api_utils.py", line 320, in a_capability_has_already_been_published_with_data
    rest_utils.send_to_url_the_data(step, url_template, world.old_capability)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/common/rest_utils.py", line 82, in send_to_url_the_data
    url = self._get_url_with_values(url_template)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/common/rest_utils.py", line 365, in _get_url_with_values
    classes_url=world.config["django"]["classes_url"],
KeyError: 'classes_url'
]]></failure></testcase><testcase classname="Endpoint Modification : Modification of an endpoint not already published_TDAFBA-487" name="| 0 | 0 | 0 | 0 |" time="5.8e-05"><failure message="classes_url"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/lettuce/core.py", line 144, in __call__
    ret = self.function(self.step, *args, **kw)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/capability_publication/endpoint_modification/steps.py", line 61, in a_capability_has_already_been_published_with_data
    api_utils.a_capability_has_already_been_published_with_data(step, old_cap_index)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/common/api_utils.py", line 320, in a_capability_has_already_been_published_with_data
    rest_utils.send_to_url_the_data(step, url_template, world.old_capability)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/common/rest_utils.py", line 82, in send_to_url_the_data
    url = self._get_url_with_values(url_template)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/common/rest_utils.py", line 365, in _get_url_with_values
    classes_url=world.config["django"]["classes_url"],
KeyError: 'classes_url'
]]></failure></testcase><testcase classname="Endpoint Modification : Modification of an endpoint with missing mandatory data" name="| 0 | 0 | 0 | 0 |" time="5.2e-05"><failure message="classes_url"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/lettuce/core.py", line 144, in __call__
    ret = self.function(self.step, *args, **kw)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/capability_publication/endpoint_modification/steps.py", line 61, in a_capability_has_already_been_published_with_data
    api_utils.a_capability_has_already_been_published_with_data(step, old_cap_index)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/common/api_utils.py", line 320, in a_capability_has_already_been_published_with_data
    rest_utils.send_to_url_the_data(step, url_template, world.old_capability)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/common/rest_utils.py", line 82, in send_to_url_the_data
    url = self._get_url_with_values(url_template)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/common/rest_utils.py", line 365, in _get_url_with_values
    classes_url=world.config["django"]["classes_url"],
KeyError: 'classes_url'
]]></failure></testcase><testcase classname="Endpoint Modification : Modification of an endpoint with missing mandatory data" name="| 0 | 0 | 1 | 0 |" time="6.1e-05"><failure message="classes_url"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/lettuce/core.py", line 144, in __call__
    ret = self.function(self.step, *args, **kw)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/capability_publication/endpoint_modification/steps.py", line 61, in a_capability_has_already_been_published_with_data
    api_utils.a_capability_has_already_been_published_with_data(step, old_cap_index)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/common/api_utils.py", line 320, in a_capability_has_already_been_published_with_data
    rest_utils.send_to_url_the_data(step, url_template, world.old_capability)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/common/rest_utils.py", line 82, in send_to_url_the_data
    url = self._get_url_with_values(url_template)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/common/rest_utils.py", line 365, in _get_url_with_values
    classes_url=world.config["django"]["classes_url"],
KeyError: 'classes_url'
]]></failure></testcase><testcase classname="Endpoint Modification : Modification of an endpoint with invalid mandatory (url and version) data_TDAFBA-473" name="| 0 | 0 | 0 | 0 | 0 |" time="6.8e-05"><failure message="classes_url"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/lettuce/core.py", line 144, in __call__
    ret = self.function(self.step, *args, **kw)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/capability_publication/endpoint_modification/steps.py", line 61, in a_capability_has_already_been_published_with_data
    api_utils.a_capability_has_already_been_published_with_data(step, old_cap_index)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/common/api_utils.py", line 320, in a_capability_has_already_been_published_with_data
    rest_utils.send_to_url_the_data(step, url_template, world.old_capability)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/common/rest_utils.py", line 82, in send_to_url_the_data
    url = self._get_url_with_values(url_template)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/common/rest_utils.py", line 365, in _get_url_with_values
    classes_url=world.config["django"]["classes_url"],
KeyError: 'classes_url'
]]></failure></testcase><testcase classname="Endpoint Modification : Modification of an endpoint with invalid mandatory (url and version) data_TDAFBA-473" name="| 0 | 0 | 1 | 0 | 0 |" time="5.1e-05"><failure message="classes_url"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/lettuce/core.py", line 144, in __call__
    ret = self.function(self.step, *args, **kw)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/capability_publication/endpoint_modification/steps.py", line 61, in a_capability_has_already_been_published_with_data
    api_utils.a_capability_has_already_been_published_with_data(step, old_cap_index)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/common/api_utils.py", line 320, in a_capability_has_already_been_published_with_data
    rest_utils.send_to_url_the_data(step, url_template, world.old_capability)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/common/rest_utils.py", line 82, in send_to_url_the_data
    url = self._get_url_with_values(url_template)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/common/rest_utils.py", line 365, in _get_url_with_values
    classes_url=world.config["django"]["classes_url"],
KeyError: 'classes_url'
]]></failure></testcase><testcase classname="Endpoint Modification : Modification of an endpoint with invalid mandatory (url and version) data_TDAFBA-473" name="| 0 | 0 | 2 | 0 | 0 |" time="5.1e-05"><failure message="classes_url"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/lettuce/core.py", line 144, in __call__
    ret = self.function(self.step, *args, **kw)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/capability_publication/endpoint_modification/steps.py", line 61, in a_capability_has_already_been_published_with_data
    api_utils.a_capability_has_already_been_published_with_data(step, old_cap_index)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/common/api_utils.py", line 320, in a_capability_has_already_been_published_with_data
    rest_utils.send_to_url_the_data(step, url_template, world.old_capability)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/common/rest_utils.py", line 82, in send_to_url_the_data
    url = self._get_url_with_values(url_template)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/common/rest_utils.py", line 365, in _get_url_with_values
    classes_url=world.config["django"]["classes_url"],
KeyError: 'classes_url'
]]></failure></testcase><testcase classname="Endpoint Modification : Modification of an endpoint with invalid mandatory (url and version) data_TDAFBA-473" name="| 0 | 0 | 3 | 0 | 0 |" time="5.2e-05"><failure message="classes_url"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/lettuce/core.py", line 144, in __call__
    ret = self.function(self.step, *args, **kw)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/capability_publication/endpoint_modification/steps.py", line 61, in a_capability_has_already_been_published_with_data
    api_utils.a_capability_has_already_been_published_with_data(step, old_cap_index)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/common/api_utils.py", line 320, in a_capability_has_already_been_published_with_data
    rest_utils.send_to_url_the_data(step, url_template, world.old_capability)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/common/rest_utils.py", line 82, in send_to_url_the_data
    url = self._get_url_with_values(url_template)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/common/rest_utils.py", line 365, in _get_url_with_values
    classes_url=world.config["django"]["classes_url"],
KeyError: 'classes_url'
]]></failure></testcase><testcase classname="Endpoint Modification : Modification of an endpoint matching another existing endpoint_TDAFBA-488" name="| 0 | 0 | 0 | 0 |" time="7.3e-05"><failure message="classes_url"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/lettuce/core.py", line 144, in __call__
    ret = self.function(self.step, *args, **kw)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/capability_publication/endpoint_modification/steps.py", line 61, in a_capability_has_already_been_published_with_data
    api_utils.a_capability_has_already_been_published_with_data(step, old_cap_index)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/common/api_utils.py", line 320, in a_capability_has_already_been_published_with_data
    rest_utils.send_to_url_the_data(step, url_template, world.old_capability)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/common/rest_utils.py", line 82, in send_to_url_the_data
    url = self._get_url_with_values(url_template)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/common/rest_utils.py", line 365, in _get_url_with_values
    classes_url=world.config["django"]["classes_url"],
KeyError: 'classes_url'
]]></failure></testcase><testcase classname="Endpoint Modification : Modification of an endpoint matching another existing endpoint_TDAFBA-488" name="| 0 | 0 | 1 | 0 |" time="5.1e-05"><failure message="classes_url"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/lettuce/core.py", line 144, in __call__
    ret = self.function(self.step, *args, **kw)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/capability_publication/endpoint_modification/steps.py", line 61, in a_capability_has_already_been_published_with_data
    api_utils.a_capability_has_already_been_published_with_data(step, old_cap_index)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/common/api_utils.py", line 320, in a_capability_has_already_been_published_with_data
    rest_utils.send_to_url_the_data(step, url_template, world.old_capability)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/common/rest_utils.py", line 82, in send_to_url_the_data
    url = self._get_url_with_values(url_template)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/common/rest_utils.py", line 365, in _get_url_with_values
    classes_url=world.config["django"]["classes_url"],
KeyError: 'classes_url'
]]></failure></testcase><testcase classname="Endpoint Modification : Addition of an endpoint with invalid optional data (attributes)" name="| 0 | 0 | 0 | 0 | 0 |" time="9.4e-05"><failure message="classes_url"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/lettuce/core.py", line 144, in __call__
    ret = self.function(self.step, *args, **kw)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/capability_publication/endpoint_modification/steps.py", line 61, in a_capability_has_already_been_published_with_data
    api_utils.a_capability_has_already_been_published_with_data(step, old_cap_index)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/common/api_utils.py", line 320, in a_capability_has_already_been_published_with_data
    rest_utils.send_to_url_the_data(step, url_template, world.old_capability)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/common/rest_utils.py", line 82, in send_to_url_the_data
    url = self._get_url_with_values(url_template)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/common/rest_utils.py", line 365, in _get_url_with_values
    classes_url=world.config["django"]["classes_url"],
KeyError: 'classes_url'
]]></failure></testcase><testcase classname="Endpoint Modification : Addition of an endpoint with invalid optional data (attributes)" name="| 0 | 0 | 1 | 0 | 0 |" time="5.2e-05"><failure message="classes_url"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/lettuce/core.py", line 144, in __call__
    ret = self.function(self.step, *args, **kw)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/capability_publication/endpoint_modification/steps.py", line 61, in a_capability_has_already_been_published_with_data
    api_utils.a_capability_has_already_been_published_with_data(step, old_cap_index)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/common/api_utils.py", line 320, in a_capability_has_already_been_published_with_data
    rest_utils.send_to_url_the_data(step, url_template, world.old_capability)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/common/rest_utils.py", line 82, in send_to_url_the_data
    url = self._get_url_with_values(url_template)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/common/rest_utils.py", line 365, in _get_url_with_values
    classes_url=world.config["django"]["classes_url"],
KeyError: 'classes_url'
]]></failure></testcase><testcase classname="Endpoint Modification : Addition of an endpoint with invalid optional data (attributes)" name="| 0 | 0 | 2 | 0 | 0 |" time="5.1e-05"><failure message="classes_url"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/lettuce/core.py", line 144, in __call__
    ret = self.function(self.step, *args, **kw)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/capability_publication/endpoint_modification/steps.py", line 61, in a_capability_has_already_been_published_with_data
    api_utils.a_capability_has_already_been_published_with_data(step, old_cap_index)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/common/api_utils.py", line 320, in a_capability_has_already_been_published_with_data
    rest_utils.send_to_url_the_data(step, url_template, world.old_capability)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/common/rest_utils.py", line 82, in send_to_url_the_data
    url = self._get_url_with_values(url_template)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/common/rest_utils.py", line 365, in _get_url_with_values
    classes_url=world.config["django"]["classes_url"],
KeyError: 'classes_url'
]]></failure></testcase><testcase classname="Endpoint Modification : Addition of an endpoint with invalid optional data (attributes)" name="| 0 | 0 | 3 | 0 | 0 |" time="5.4e-05"><failure message="classes_url"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/lettuce/core.py", line 144, in __call__
    ret = self.function(self.step, *args, **kw)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/capability_publication/endpoint_modification/steps.py", line 61, in a_capability_has_already_been_published_with_data
    api_utils.a_capability_has_already_been_published_with_data(step, old_cap_index)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/common/api_utils.py", line 320, in a_capability_has_already_been_published_with_data
    rest_utils.send_to_url_the_data(step, url_template, world.old_capability)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/common/rest_utils.py", line 82, in send_to_url_the_data
    url = self._get_url_with_values(url_template)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/common/rest_utils.py", line 365, in _get_url_with_values
    classes_url=world.config["django"]["classes_url"],
KeyError: 'classes_url'
]]></failure></testcase><testcase classname="Endpoint Modification : Addition of an endpoint with invalid optional data (attributes)" name="| 0 | 0 | 4 | 0 | 0 |" time="5.2e-05"><failure message="classes_url"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/lettuce/core.py", line 144, in __call__
    ret = self.function(self.step, *args, **kw)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/capability_publication/endpoint_modification/steps.py", line 61, in a_capability_has_already_been_published_with_data
    api_utils.a_capability_has_already_been_published_with_data(step, old_cap_index)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/common/api_utils.py", line 320, in a_capability_has_already_been_published_with_data
    rest_utils.send_to_url_the_data(step, url_template, world.old_capability)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/common/rest_utils.py", line 82, in send_to_url_the_data
    url = self._get_url_with_values(url_template)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/common/rest_utils.py", line 365, in _get_url_with_values
    classes_url=world.config["django"]["classes_url"],
KeyError: 'classes_url'
]]></failure></testcase><testcase classname="Endpoint Modification : Addition of an endpoint with invalid optional data (attributes)" name="| 0 | 0 | 5 | 0 | 0 |" time="5.1e-05"><failure message="classes_url"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/lettuce/core.py", line 144, in __call__
    ret = self.function(self.step, *args, **kw)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/capability_publication/endpoint_modification/steps.py", line 61, in a_capability_has_already_been_published_with_data
    api_utils.a_capability_has_already_been_published_with_data(step, old_cap_index)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/common/api_utils.py", line 320, in a_capability_has_already_been_published_with_data
    rest_utils.send_to_url_the_data(step, url_template, world.old_capability)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/common/rest_utils.py", line 82, in send_to_url_the_data
    url = self._get_url_with_values(url_template)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/common/rest_utils.py", line 365, in _get_url_with_values
    classes_url=world.config["django"]["classes_url"],
KeyError: 'classes_url'
]]></failure></testcase><testcase classname="Endpoint Modification : Addition of an endpoint with invalid optional data (attributes)" name="| 0 | 0 | 6 | 0 | 0 |" time="6.7e-05"><failure message="classes_url"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/lettuce/core.py", line 144, in __call__
    ret = self.function(self.step, *args, **kw)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/capability_publication/endpoint_modification/steps.py", line 61, in a_capability_has_already_been_published_with_data
    api_utils.a_capability_has_already_been_published_with_data(step, old_cap_index)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/common/api_utils.py", line 320, in a_capability_has_already_been_published_with_data
    rest_utils.send_to_url_the_data(step, url_template, world.old_capability)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/common/rest_utils.py", line 82, in send_to_url_the_data
    url = self._get_url_with_values(url_template)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/common/rest_utils.py", line 365, in _get_url_with_values
    classes_url=world.config["django"]["classes_url"],
KeyError: 'classes_url'
]]></failure></testcase><testcase classname="Endpoint Modification : Addition of an endpoint with invalid optional data (attributes)" name="| 0 | 0 | 7 | 0 | 0 |" time="5.2e-05"><failure message="classes_url"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/lettuce/core.py", line 144, in __call__
    ret = self.function(self.step, *args, **kw)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/capability_publication/endpoint_modification/steps.py", line 61, in a_capability_has_already_been_published_with_data
    api_utils.a_capability_has_already_been_published_with_data(step, old_cap_index)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/common/api_utils.py", line 320, in a_capability_has_already_been_published_with_data
    rest_utils.send_to_url_the_data(step, url_template, world.old_capability)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/common/rest_utils.py", line 82, in send_to_url_the_data
    url = self._get_url_with_values(url_template)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/common/rest_utils.py", line 365, in _get_url_with_values
    classes_url=world.config["django"]["classes_url"],
KeyError: 'classes_url'
]]></failure></testcase><testcase classname="Endpoint Modification : Addition of an endpoint with invalid optional data (attributes)" name="| 0 | 0 | 8 | 0 | 0 |" time="5.1e-05"><failure message="classes_url"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/lettuce/core.py", line 144, in __call__
    ret = self.function(self.step, *args, **kw)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/capability_publication/endpoint_modification/steps.py", line 61, in a_capability_has_already_been_published_with_data
    api_utils.a_capability_has_already_been_published_with_data(step, old_cap_index)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/common/api_utils.py", line 320, in a_capability_has_already_been_published_with_data
    rest_utils.send_to_url_the_data(step, url_template, world.old_capability)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/common/rest_utils.py", line 82, in send_to_url_the_data
    url = self._get_url_with_values(url_template)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/common/rest_utils.py", line 365, in _get_url_with_values
    classes_url=world.config["django"]["classes_url"],
KeyError: 'classes_url'
]]></failure></testcase><testcase classname="Endpoint Modification : Addition of an endpoint with invalid optional data (duplicated attributes)" name="| 0 | 0 | 0 | 0 | 0 |" time="7.5e-05"><failure message="classes_url"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/lettuce/core.py", line 144, in __call__
    ret = self.function(self.step, *args, **kw)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/capability_publication/endpoint_modification/steps.py", line 61, in a_capability_has_already_been_published_with_data
    api_utils.a_capability_has_already_been_published_with_data(step, old_cap_index)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/common/api_utils.py", line 320, in a_capability_has_already_been_published_with_data
    rest_utils.send_to_url_the_data(step, url_template, world.old_capability)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/common/rest_utils.py", line 82, in send_to_url_the_data
    url = self._get_url_with_values(url_template)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/common/rest_utils.py", line 365, in _get_url_with_values
    classes_url=world.config["django"]["classes_url"],
KeyError: 'classes_url'
]]></failure></testcase><testcase classname="Endpoint Modification : Modification of an endpoint with valid mandatory data_TDAFBA-480" name="| 0 | 0 | 0 |" time="7.2e-05"><failure message="classes_url"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/lettuce/core.py", line 144, in __call__
    ret = self.function(self.step, *args, **kw)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/capability_publication/endpoint_modification/steps.py", line 61, in a_capability_has_already_been_published_with_data
    api_utils.a_capability_has_already_been_published_with_data(step, old_cap_index)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/common/api_utils.py", line 320, in a_capability_has_already_been_published_with_data
    rest_utils.send_to_url_the_data(step, url_template, world.old_capability)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/common/rest_utils.py", line 82, in send_to_url_the_data
    url = self._get_url_with_values(url_template)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/common/rest_utils.py", line 365, in _get_url_with_values
    classes_url=world.config["django"]["classes_url"],
KeyError: 'classes_url'
]]></failure></testcase><testcase classname="Endpoint Modification : Modification of an endpoint with valid mandatory data_TDAFBA-480" name="| 0 | 1 | 0 |" time="5.1e-05"><failure message="classes_url"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/lettuce/core.py", line 144, in __call__
    ret = self.function(self.step, *args, **kw)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/capability_publication/endpoint_modification/steps.py", line 61, in a_capability_has_already_been_published_with_data
    api_utils.a_capability_has_already_been_published_with_data(step, old_cap_index)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/common/api_utils.py", line 320, in a_capability_has_already_been_published_with_data
    rest_utils.send_to_url_the_data(step, url_template, world.old_capability)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/common/rest_utils.py", line 82, in send_to_url_the_data
    url = self._get_url_with_values(url_template)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/common/rest_utils.py", line 365, in _get_url_with_values
    classes_url=world.config["django"]["classes_url"],
KeyError: 'classes_url'
]]></failure></testcase><testcase classname="Endpoint Modification : Modification of an endpoint with valid mandatory data_TDAFBA-480" name="| 0 | 2 | 0 |" time="5e-05"><failure message="classes_url"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/lettuce/core.py", line 144, in __call__
    ret = self.function(self.step, *args, **kw)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/capability_publication/endpoint_modification/steps.py", line 61, in a_capability_has_already_been_published_with_data
    api_utils.a_capability_has_already_been_published_with_data(step, old_cap_index)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/common/api_utils.py", line 320, in a_capability_has_already_been_published_with_data
    rest_utils.send_to_url_the_data(step, url_template, world.old_capability)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/common/rest_utils.py", line 82, in send_to_url_the_data
    url = self._get_url_with_values(url_template)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/common/rest_utils.py", line 365, in _get_url_with_values
    classes_url=world.config["django"]["classes_url"],
KeyError: 'classes_url'
]]></failure></testcase><testcase classname="Endpoint Modification : Modification of an endpoint with valid mandatory and optional data_TDAFBA-481" name="| 0 | 0 | 0 |" time="8.5e-05"><failure message="classes_url"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/lettuce/core.py", line 144, in __call__
    ret = self.function(self.step, *args, **kw)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/capability_publication/endpoint_modification/steps.py", line 61, in a_capability_has_already_been_published_with_data
    api_utils.a_capability_has_already_been_published_with_data(step, old_cap_index)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/common/api_utils.py", line 320, in a_capability_has_already_been_published_with_data
    rest_utils.send_to_url_the_data(step, url_template, world.old_capability)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/common/rest_utils.py", line 82, in send_to_url_the_data
    url = self._get_url_with_values(url_template)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/common/rest_utils.py", line 365, in _get_url_with_values
    classes_url=world.config["django"]["classes_url"],
KeyError: 'classes_url'
]]></failure></testcase><testcase classname="Endpoint Modification : Modification of an endpoint with valid mandatory and optional data_TDAFBA-481" name="| 0 | 1 | 0 |" time="5.1e-05"><failure message="classes_url"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/lettuce/core.py", line 144, in __call__
    ret = self.function(self.step, *args, **kw)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/capability_publication/endpoint_modification/steps.py", line 61, in a_capability_has_already_been_published_with_data
    api_utils.a_capability_has_already_been_published_with_data(step, old_cap_index)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/common/api_utils.py", line 320, in a_capability_has_already_been_published_with_data
    rest_utils.send_to_url_the_data(step, url_template, world.old_capability)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/common/rest_utils.py", line 82, in send_to_url_the_data
    url = self._get_url_with_values(url_template)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/common/rest_utils.py", line 365, in _get_url_with_values
    classes_url=world.config["django"]["classes_url"],
KeyError: 'classes_url'
]]></failure></testcase><testcase classname="Endpoint Modification : Modification of an endpoint with valid mandatory and optional data_TDAFBA-481" name="| 0 | 2 | 0 |" time="7.3e-05"><failure message="classes_url"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/lettuce/core.py", line 144, in __call__
    ret = self.function(self.step, *args, **kw)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/capability_publication/endpoint_modification/steps.py", line 61, in a_capability_has_already_been_published_with_data
    api_utils.a_capability_has_already_been_published_with_data(step, old_cap_index)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/common/api_utils.py", line 320, in a_capability_has_already_been_published_with_data
    rest_utils.send_to_url_the_data(step, url_template, world.old_capability)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/common/rest_utils.py", line 82, in send_to_url_the_data
    url = self._get_url_with_values(url_template)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/common/rest_utils.py", line 365, in _get_url_with_values
    classes_url=world.config["django"]["classes_url"],
KeyError: 'classes_url'
]]></failure></testcase><testcase classname="Endpoint Modification : Modification of an endpoint with valid mandatory and optional data_TDAFBA-481" name="| 0 | 3 | 0 |" time="5.1e-05"><failure message="classes_url"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/lettuce/core.py", line 144, in __call__
    ret = self.function(self.step, *args, **kw)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/capability_publication/endpoint_modification/steps.py", line 61, in a_capability_has_already_been_published_with_data
    api_utils.a_capability_has_already_been_published_with_data(step, old_cap_index)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/common/api_utils.py", line 320, in a_capability_has_already_been_published_with_data
    rest_utils.send_to_url_the_data(step, url_template, world.old_capability)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/common/rest_utils.py", line 82, in send_to_url_the_data
    url = self._get_url_with_values(url_template)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/common/rest_utils.py", line 365, in _get_url_with_values
    classes_url=world.config["django"]["classes_url"],
KeyError: 'classes_url'
]]></failure></testcase><testcase classname="Endpoint Modification : Modification of an endpoint with valid mandatory and optional data_TDAFBA-481" name="| 0 | 4 | 0 |" time="5.1e-05"><failure message="classes_url"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/lettuce/core.py", line 144, in __call__
    ret = self.function(self.step, *args, **kw)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/capability_publication/endpoint_modification/steps.py", line 61, in a_capability_has_already_been_published_with_data
    api_utils.a_capability_has_already_been_published_with_data(step, old_cap_index)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/common/api_utils.py", line 320, in a_capability_has_already_been_published_with_data
    rest_utils.send_to_url_the_data(step, url_template, world.old_capability)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/common/rest_utils.py", line 82, in send_to_url_the_data
    url = self._get_url_with_values(url_template)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/common/rest_utils.py", line 365, in _get_url_with_values
    classes_url=world.config["django"]["classes_url"],
KeyError: 'classes_url'
]]></failure></testcase><testcase classname="Endpoint Modification : Modification of an endpoint adding optional data that was not there_TDAFBA-482" name="| 0 | 0 | 0 |" time="5.1e-05"><failure message="classes_url"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/lettuce/core.py", line 144, in __call__
    ret = self.function(self.step, *args, **kw)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/capability_publication/endpoint_modification/steps.py", line 61, in a_capability_has_already_been_published_with_data
    api_utils.a_capability_has_already_been_published_with_data(step, old_cap_index)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/common/api_utils.py", line 320, in a_capability_has_already_been_published_with_data
    rest_utils.send_to_url_the_data(step, url_template, world.old_capability)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/common/rest_utils.py", line 82, in send_to_url_the_data
    url = self._get_url_with_values(url_template)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/common/rest_utils.py", line 365, in _get_url_with_values
    classes_url=world.config["django"]["classes_url"],
KeyError: 'classes_url'
]]></failure></testcase><testcase classname="Endpoint Modification : Modification of an endpoint with a new api_name which is ignored_TDAFBA-483" name="| 0 | 0 | 0 |" time="5.8e-05"><failure message="classes_url"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/lettuce/core.py", line 144, in __call__
    ret = self.function(self.step, *args, **kw)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/capability_publication/endpoint_modification/steps.py", line 61, in a_capability_has_already_been_published_with_data
    api_utils.a_capability_has_already_been_published_with_data(step, old_cap_index)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/common/api_utils.py", line 320, in a_capability_has_already_been_published_with_data
    rest_utils.send_to_url_the_data(step, url_template, world.old_capability)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/common/rest_utils.py", line 82, in send_to_url_the_data
    url = self._get_url_with_values(url_template)
  File "/Users/eag/workspace/tdaf-servicedirectory/test/acceptance/src/e2e/common/rest_utils.py", line 365, in _get_url_with_values
    classes_url=world.config["django"]["classes_url"],
KeyError: 'classes_url'
]]></failure></testcase></testsuite>